version: '2'
services:
    ramadama-app:
        image: ramadama
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ramadama-postgresql:5432/ramadama
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ramadama-postgresql:
        extends:
            file: postgresql.yml
            service: ramadama-postgresql
